services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MARIADB_DATABASE=${DATABASE}
      - MARIADB_PASSWORD=${PASSWORD}
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MARIADB_USER=${USERNAME}
    ports:
      - '3306'
